# ワークフローの名前
name: Continuous Integration
# ワークフローを実行するイベント
on: 
  workflow_dispatch:
    inputs:
      node_version: 
        default: node -p -e '`${require("./package.json").volta.node}`' 
        required: false
        description: 'version of nodejs'

jobs:
  # job_id 重複はNG
  unit-test:
    # ジョブの名前
    name: Unit Test
    # ジョブが実行されるマシンの定義
    runs-on: ubuntu-latest
    # timeout時間(単位はminute,デフォルトで360分)
    timeout-minutes: 360
    # ジョブが実行するステップの定義
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Node Version
        run: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  lint:
    name: linte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

