# ワークフローの名前
name: Hello,World!

# push時に実行
on: 
  workflow_dispatch:
    inputs: {}

# 実行するjob
jobs:
  build:
    name: Greeting
    # jobが実行される仮想環境を指定
    runs-on: ubuntu-latest
    # job内で実行される処理を指定
    steps:
      - uses: actions/checkout@v3
      - name: say hello
        run: |
          echo "Hello!!!!!" 
          echo "qwertyuiop" 
